Models/Department.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models
{
    public class Department
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Deptid { get; set; }
        public string Deptname { get; set; }

        public ICollection<Student> Students { get; set; } = new HashSet<Student>();
        public ICollection<Course> Courses { get; set; } = new HashSet<Course>();

    }
}

Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Models;
using WebApplication2.Repositories;

namespace WebApplication2.Controllers
{
    [Authorize (Roles ="Admin,Instructor")]
    public class DepartmentController : Controller
    {
        IDepartpentCourseRepo dptcrsrepo;
        IDeptRepo dptrepo; 
        public DepartmentController(IDepartpentCourseRepo _dptcrsrepo,IDeptRepo _dptrepo)
        {
            dptcrsrepo= _dptcrsrepo; 
            dptrepo= _dptrepo;  
        }
        public IActionResult Index()
        {
            var Deps = dptrepo.GetAllDepartments();  
            if (Deps == null)
                return Content("Error");
            else
                return View(Deps);
        }
        public IActionResult Create()
        {
            ViewBag.Courses = dptcrsrepo.GetAllCourses();
            return View();
        }
        [HttpPost]
        public IActionResult Create(Department dpt,List<int> Coursesindept)
        { 
                foreach(var item in Coursesindept)
                {
                var c = dptcrsrepo.GetCourseByID(item);
                dpt.Courses.Add(c);
                }
            dptcrsrepo.AddDepartmnet(dpt);
            return RedirectToAction("Index","Department");
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return BadRequest();
            Department dept= dptrepo.GetDepartmentById(id.Value);
            if (dept == null)
                return NotFound();
            return View(dept);
        }
        [HttpPost]
        public IActionResult Edit(int id , Department dpt)
        {
            dpt.Deptid = id;
            dptrepo.UpdateDepartment(dpt);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return BadRequest();
            var dpt = dptcrsrepo.GetDepartmentById(id.Value);
            if (dpt == null)
                return NotFound();
            dptrepo.DeleteDepartment(dpt);  
            return RedirectToAction("Index","Department");
        }
    }
    
}

Controllers/DepartmentCoursesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Models;
using WebApplication2.Repositories;

namespace WebApplication2.Controllers
{
    [Authorize]
    public class DepartmentCoursesController : Controller
    {
        IDepartpentCourseRepo dptcrsrepo;
        IStudentCourseRepo stdcrsrepo;
        public DepartmentCoursesController(IDepartpentCourseRepo _dptcrsrepo, IStudentCourseRepo _stdcrsrepo)
        {
            dptcrsrepo = _dptcrsrepo;
            stdcrsrepo = _stdcrsrepo;
        }
        public IActionResult ShowCourses(int? id)
        {
            Department dept = dptcrsrepo.GetDepartmentById(id.Value);
            return View(dept);
        }
        public IActionResult ManageCourses(int? id)
        {
            Department dept = dptcrsrepo.GetDepartmentById(id.Value);
            var allcourses = dptcrsrepo.GetAllCourses();    
            var CoursesInDept = dept.Courses;
            var CoursesNotInDept =allcourses.Except(CoursesInDept);
            ViewBag.CoursesNotInDept = CoursesNotInDept;
            return View(dept);  
        }
        [HttpPost]
        public IActionResult ManageCourses(int? id,List<int> CoursestoRemove,List<int> CoursestoAdd)
        {
            Department dept = dptcrsrepo.GetDepartmentById(id.Value);
            foreach (var item in CoursestoRemove)
            {
                Course c = dptcrsrepo.GetCourseByID(item);
                dptcrsrepo.RemoveCoursestoDept(dept, c);
            }
            foreach(var item in CoursestoAdd)
            {
                Course c = dptcrsrepo.GetCourseByID(item);
                dptcrsrepo.AddCoursestoDept(dept,c);    
            }
            return RedirectToAction("Index","Department");
        }
        public IActionResult AddDegree(int deptid, int corsid)
        {
            Department dept = dptcrsrepo.GetDepartmentById(deptid);
            Course crs = dptcrsrepo.GetCourseByID(corsid);
            ViewBag.Course = crs;
            return View(dept);
        }
        [HttpPost]
        public IActionResult AddDegree(int corsid ,Dictionary<int,int>degree)
        {
            foreach(var item in degree)
            {
                StudentCourse stdcrs = stdcrsrepo.GetStudentCoursebyId(item.Key,corsid);
                if(stdcrs==null)
                {
                    StudentCourse studentCourse = new StudentCourse()
                    { Stdid = item.Key, Crsid = corsid, degree = item.Value };
                    stdcrsrepo.AddStudentCourse(studentCourse);
                }
                else
                    stdcrs.degree = item.Value;
            }
            return RedirectToAction("index", "Department");
        }
    }
}

Views/Department/Create.cshtml
@model Department
@{
    Layout = null;
    SelectList Courses = new SelectList(ViewBag.Courses, "Id", "Name");
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body class="container">
    <form method="post">

        <label asp-for="Deptid">Department ID</label>
        <br />
        <input asp-for="Deptid" />
        <br />
        <label asp-for="Deptname">Department name</label>
        <br />
        <input asp-for="Deptname" />
        <br />
        <label>Courses</label>
        <br />
        <select multiple asp-items="Courses" name="Coursesindept"></select>
        <br />
        <input type="submit" value="add" class="btn btn-info" />
    </form>
</body>
</html>

Views/Department/Edit.cshtml
@{
    Layout = null;
}
@model Department
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body class="container">
    <form method="post">
        <label asp-for="Deptname"></label>
        <br />
        <input asp-for="Deptname" />
        <input type="submit" value="Edit" class="btn btn-info" />
    </form>
</body>
</html>

Views/Department/Index.cshtml
@model IEnumerable<Department>
@{
    Layout = null;
    int i = 1;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />

</head>
<body class="container">
    <table class="table table-light table-hover mt-5 align-items-center">
        <thead>
            <tr>
                <th>#</th>
                <th>Department ID</th>
                <th>Department name</th>
                <th>Number of Students</th>
                <th>Number of Courses</th>
                <th>Operations</th>

            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>@(i++)</td>
                    <td>@item.Deptid</td>
                    <td>@item.Deptname</td>
                    <td>@item.Students.Count</td>
                    <td>@item.Courses.Count</td>
                    <td>
                        <a asp-action="Edit" asp-controller="Department" asp-route-id="@item.Deptid" class="btn btn-warning">Edit</a>
                        <a asp-action="Delete" asp-controller="Department" asp-route-id="@item.Deptid" class="btn btn-danger">Delete</a>
                        <a asp-action="ShowCourses" asp-controller="DepartmentCourses" asp-route-id="@item.Deptid" class="btn btn-danger">Show Courses</a>
                        <a asp-action="ManageCourses" asp-controller="DepartmentCourses" asp-route-id="@item.Deptid" class="btn btn-dark">Manage Courses</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a href="/Department/Create" class="btn btn-dark">Create</a>

    @* ---------------------------------------------------------------------------------------- *@

    <script src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/lib/jquery/dist/jquery.js"></script>
   
</body>
</html>